// const langCodes = {
//     af: "Afrikaans",
//     sq: "Albanian",
//     am: "Amharic",
//     ar: "Arabic",
//     hy: "Armenian",
//     az: "Azerbaijani",
//     eu: "Basque",
//     be: "Belarusian",
//     // bem: 'Bemba',
//     // bn: 'Bengali',
//     // bh: 'Bihari',
//     // 'xx-bork': 'Bork, bork, bork!',
//     bs: "Bosnian",
//     // br: 'Breton',
//     bg: "Bulgarian",
//     // burmese,
//     // km: 'Cambodian',
//     ca: "Catalan",
//     // cebuano,
//     // chr: 'Cherokee',
//     // ny: 'Chichewa',
//     "zh-CN": "Chinese (Simplified)",
//     "zh-TW": "Chinese (Traditional)",
//     co: "Corsican",
//     hr: "Croatian",
//     cs: "Czech",
//     da: "Danish",
//     nl: "Dutch",
//     // 'xx-elmer': 'Elmer Fudd',
//     en: "English",
//     eo: "Esperanto",
//     et: "Estonian",
//     // ee: 'Ewe',
//     // fo: 'Faroese',
//     tl: "Filipino",
//     fi: "Finnish",
//     fr: "French",
//     // fy: 'Frisian',
//     // gaa: 'Ga',
//     // gl: 'Galician',
//     ka: "Georgian",
//     de: "German",
//     el: "Greek",
//     // gn: 'Guarani',
//     gu: "Gujarati",
//     // 'xx-hacker': 'Hacker',
//     ht: "Haitian Creole",
//     ha: "Hausa",
//     haw: "Hawaiian",
//     iw: "Hebrew",
//     hi: "Hindi",
//     //// hmong
//     hu: "Hungarian",
//     is: "Icelandic",
//     ig: "Igbo",
//     id: "Indonesian",
//     // ia: 'Interlingua',
//     ga: "Irish",
//     it: "Italian",
//     ja: "Japanese",
//     jw: "Javanese",
//     kn: "Kannada",
//     kk: "Kazakh",
//     ///// khmer
//     rw: "Kinyarwanda",
//     // rn: 'Kirundi',
//     // 'xx-klingon': 'Klingon',
//     // kg: 'Kongo',
//     ko: "Korean",
//     // kri: 'Krio (Sierra Leone)',
//     ku: "Kurdish",
//     // ckb: 'Kurdish (Soranî)',
//     ky: "Kyrgyz",
//     lo: "Laothian",
//     la: "Latin",
//     lv: "Latvian",
//     // ln: 'Lingala',
//     lt: "Lithuanian",
//     //// Luxemburgish
//     // loz: 'Lozi',
//     // lg: 'Luganda',
//     // ach: 'Luo',
//     mk: "Macedonian",
//     mg: "Malagasy",
//     ms: "Malay",
//     ml: "Malayalam",
//     mt: "Maltese",
//     mi: "Maori",
//     mr: "Marathi",
//     // mfe: 'Mauritian Creole',
//     // mo: 'Moldavian',
//     // mn: 'Mongolian',
//     // 'sr-ME': 'Montenegrin',
//     ne: "Nepali",
//     // pcm: 'Nigerian Pidgin',
//     // nso: 'Northern Sotho',
//     no: "Norwegian",
//     // nn: 'Norwegian (Nynorsk)',
//     ////// nyanja
//     // oc: 'Occitan',
//     // or: 'Oriya',
//     // om: 'Oromo',
//     //////odia
//     ps: "Pashto",
//     fa: "Persian",
//     // 'xx-pirate': 'Pirate',
//     pl: "Polish",
//     "pt-BR": "Portuguese (Brazil)",
//     "pt-PT": "Portuguese (Portugal)",
//     pa: "Punjabi",
//     // qu: 'Quechua',
//     ro: "Romanian",
//     // rm: 'Romansh',
//     // nyn: 'Runyakitara',
//     ru: "Russian",
//     ///// samoan
//     gd: "Scots Gaelic",
//     sr: "Serbian",
//     // sh: 'Serbo-Croatian',
//     // st: 'Sesotho',
//     // tn: 'Setswana',
//     // crs: 'Seychellois Creole',
//     sn: "Shona",
//     sd: "Sindhi",
//     si: "Sinhalese",
//     sk: "Slovak",
//     sl: "Slovenian",
//     so: "Somali",
//     ////// southern sotho
//     es: "Spanish",
//     // 'es-419': 'Spanish (Latin American)',
//     su: "Sundanese",
//     sw: "Swahili",
//     sv: "Swedish",
//     tg: "Tajik",
//     ta: "Tamil",
//     tt: "Tatar",
//     te: "Telugu",
//     th: "Thai",
//     // ti: 'Tigrinya',
//     // to: 'Tonga',
//     // lua: 'Tshiluba',
//     // tum: 'Tumbuka',
//     tr: "Turkish",
//     tk: "Turkmen",
//     // tw: 'Twi',
//     // ug: 'Uighur',
//     uk: "Ukrainian",
//     ur: "Urdu",
//     ///// uyghur
//     uz: "Uzbek",
//     vi: "Vietnamese",
//     cy: "Welsh",
//     // wo: 'Wolof',
//     /////// wesyern frisian
//     xh: "Xhosa",
//     yi: "Yiddish",
//     yo: "Yoruba",
//     zu: "Zulu"
// };
const langCodes = {
    ar: "Arabic",
    "zh-CN": "Chinese (Simplified)",
    "zh-TW": "Chinese (Traditional)",
    nl: "Dutch",
    en: "English",
    fr: "French",
    de: "German",
    hu: "Hungarian",
    id: "Indonesian",
    it: "Italian",
    ja: "Japanese",
    ko: "Korean",
    "pt-BR": "Portuguese (Brazil)",
    "pt-PT": "Portuguese (Portugal)",
    ru: "Russian",
    es: "Spanish",
};
// const dataLang = [
//     'ar-AR_OmarVoice',
//     'de-DE_BirgitV3Voice',
//     'de-DE_DieterV3Voice',
//     'de-DE_ErikaV3Voice',
//     'en-GB_KateV3Voice',
//     'en-US_AllisonV3Voice',
//     'en-US_EmilyV3Voice',
//     'en-US_HenryV3Voice',
//     'en-US_KevinV3Voice',
//     'en-US_LisaV3Voice',
//     'en-US_MichaelV3Voice',
//     'en-US_OliviaV3Voice',
//     'es-ES_EnriqueV3Voice',
//     'es-ES_LauraV3Voice',
//     'es-LA_SofiaV3Voice',
//     'es-US_SofiaV3Voice',
//     'fr-FR_ReneeV3Voice',
//     'it-IT_FrancescaV3Voice',
//     'ja-JP_EmiV3Voice',
//     'nl-NL_EmmaVoice',
//     'nl-NL_LiamVoice',
//     'pt-BR_IsabelaV3Voice',
//     'zh-CN_LiNaVoice',
//     'zh-CN_WangWeiVoice',
//     'zh-CN_ZhangJingVoice'
// ]

const langSpeakers = {
    ar: { "ar-AR_OmarVoice": "AR - Omar" },
    de: {
        "de-DE_BirgitV3Voice": "DE - BirgitV3",
        "de-DE_DieterV3Voice": "DE - DieterV3",
        "de-DE_ErikaV3Voice": "DE - ErikaV3"
    },
    en: {
        "en-GB_KateV3Voice": "GB - KateV3",
        "en-US_AllisonV3Voice": "US - AllisonV3",
        "en-US_EmilyV3Voice": "US - EmilyV3",
        "en-US_HenryV3Voice": "US - HenryV3",
        "en-US_KevinV3Voice": "US - KevinV3",
        "en-US_LisaV3Voice": "US - LisaV3",
        "en-US_MichaelV3Voice": "US - MichaelV3",
        "en-US_OliviaV3Voice": "US - OliviaV3"
    },
    es: {
        "es-ES_EnriqueV3Voice": "ES - EnriqueV3",
        "es-ES_LauraV3Voice": "ES - LauraV3",
        "es-LA_SofiaV3Voice": "LA - SofiaV3",
        "es-US_SofiaV3Voice": "US - SofiaV3"
    },
    fr: { "fr-FR_ReneeV3Voice": "FR - ReneeV3" },
    it: { "it-IT_FrancescaV3Voice": "IT - FrancescaV3" },
    ja: { "ja-JP_EmiV3Voice": "JP - EmiV3" },
    nl: {
        "nl-NL_EmmaVoice": "NL - Emma",
        "nl-NL_LiamVoice": "NL - Liam"
    },
    pt: { "pt-BR_IsabelaV3Voice": "BR - IsabelaV3" },
    zh: {
        "zh-CN_LiNaVoice": "CN - LiNa",
        "zh-CN_WangWeiVoice": "CN - WangWei",
        "zh-CN_ZhangJingVoice": "CN - ZhangJing"
    }
};
const langNames = {
    ar: "Arabic",
    de: "German",
    en: "English",
    es: "Spanish",
    fr: "French",
    it: "Italian",
    ja: "Japanese",
    nl: "Dutch",
    pt: "Portuguese",
    zh: "Chinese"
};
